// Comprehensive facility data for Central Uganda
const facilitiesData = [
{
        id: 188,
        name: "Masaka Internet Cafe",
        type: "Internet Cafe",
        category: "Technology",
        contact: "+256-481-421900",
        coordinates: [-0.3040, 31.6990],
        address: "Masaka Town, Masaka",
        services: ["Internet Access", "Printing", "Photocopying", "Computer Training"],
        district: "Masaka",
        openingHours: "Daily: 8AM-10PM",
        rating: 3.5
    },
    // BUTAMBALA DISTRICT - Additional Facilities
    {
        id: 189,
        name: "Butambala District Hospital",
        type: "Hospital",
        category: "Healthcare",
        contact: "+256-772-234562",
        coordinates: [0.1850, 32.3550],
        address: "Butambala Town",
        services: ["Emergency", "Surgery", "Maternity", "Outpatient"],
        district: "Butambala",
        beds: 85,
        openingHours: "24/7",
        rating: 3.5
    },
    {
        id: 190,
        name: "Butambala Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-345673",
        coordinates: [0.1770, 32.3470],
        address: "Butambala Town",
        students: 600,
        district: "Butambala",
        rating: 3.6
    },
    {
        id: 191,
        name: "Gombe Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-456784",
        coordinates: [0.1900, 32.3600],
        address: "Gombe, Butambala",
        services: ["Primary Care", "First Aid"],
        district: "Butambala",
        rating: 3.1
    },
    {
        id: 192,
        name: "Gombe Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-567895",
        coordinates: [0.1920, 32.3620],
        address: "Gombe, Butambala",
        district: "Butambala",
        openingHours: "24/7",
        officers: 15
    },
    {
        id: 193,
        name: "Gombe Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-678906",
        coordinates: [0.1880, 32.3580],
        address: "Gombe, Butambala",
        students: 380,
        district: "Butambala",
        rating: 3.4
    },
    {
        id: 194,
        name: "Kibibi Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-789017",
        coordinates: [0.1700, 32.3400],
        address: "Kibibi, Butambala",
        services: ["Outpatient", "Maternity", "Immunization"],
        district: "Butambala",
        rating: 3.2
    },
    {
        id: 195,
        name: "Kibibi Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-890128",
        coordinates: [0.1680, 32.3380],
        address: "Kibibi, Butambala",
        students: 420,
        district: "Butambala",
        rating: 3.5
    },
    // BUIKWE DISTRICT - Additional Facilities
    {
        id: 196,
        name: "Buikwe Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-670201",
        coordinates: [0.3280, 32.9850],
        address: "Buikwe Town",
        services: ["Primary Care", "Immunization"],
        district: "Buikwe",
        rating: 3.4
    },
    {
        id: 197,
        name: "Buikwe Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-670202",
        coordinates: [0.3270, 32.9820],
        address: "Buikwe Town",
        students: 650,
        district: "Buikwe",
        rating: 3.9
    },
    {
        id: 198,
        name: "Buikwe Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-670203",
        coordinates: [0.3230, 32.9780],
        address: "Buikwe Town",
        students: 450,
        district: "Buikwe",
        rating: 3.7
    },
    {
        id: 199,
        name: "Lugazi General Hospital",
        type: "Hospital",
        category: "Healthcare",
        contact: "+256-414-771001",
        coordinates: [0.3730, 32.9200],
        address: "Lugazi Town, Buikwe",
        services: ["Emergency", "Surgery", "Maternity", "ICU"],
        district: "Buikwe",
        beds: 180,
        openingHours: "24/7",
        rating: 4.0
    },
    {
        id: 200,
        name: "Lugazi Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-771501",
        coordinates: [0.3680, 32.9130],
        address: "Lugazi, Buikwe",
        students: 550,
        district: "Buikwe",
        rating: 3.9
    },
    {
        id: 201,
        name: "Najjembe Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-445501",
        coordinates: [0.4450, 33.1850],
        address: "Najjembe, Buikwe",
        services: ["Outpatient", "Maternity"],
        district: "Buikwe",
        rating: 3.3
    },
    {
        id: 202,
        name: "Njeru Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-445502",
        coordinates: [0.4440, 33.1820],
        address: "Njeru Municipality, Buikwe",
        district: "Buikwe",
        openingHours: "24/7",
        officers: 55
    },
    {
        id: 203,
        name: "Njeru Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-445503",
        coordinates: [0.4400, 33.1780],
        address: "Njeru Municipality, Buikwe",
        students: 720,
        district: "Buikwe",
        rating: 3.8
    },
    {
        id: 204,
        name: "Nkokonjeru Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-771002",
        coordinates: [0.3500, 32.9500],
        address: "Nkokonjeru, Buikwe",
        services: ["Primary Care", "Laboratory"],
        district: "Buikwe",
        rating: 3.5
    },
    {
        id: 205,
        name: "Nkokonjeru Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-771003",
        coordinates: [0.3520, 32.9520],
        address: "Nkokonjeru, Buikwe",
        students: 580,
        district: "Buikwe",
        rating: 3.7
    },
    // GOMBA DISTRICT - Additional Facilities
    {
        id: 206,
        name: "Gomba Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-778801",
        coordinates: [0.2130, 31.6530],
        address: "Gomba Town",
        students: 480,
        district: "Gomba",
        rating: 3.5
    },
    {
        id: 207,
        name: "Maddu Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-556601",
        coordinates: [0.2200, 31.6600],
        address: "Maddu, Gomba",
        services: ["Outpatient", "Maternity"],
        district: "Gomba",
        rating: 3.3
    },
    {
        id: 208,
        name: "Maddu Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-667701",
        coordinates: [0.2220, 31.6620],
        address: "Maddu, Gomba",
        district: "Gomba",
        openingHours: "24/7",
        officers: 20
    },
    {
        id: 209,
        name: "Maddu Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-778802",
        coordinates: [0.2180, 31.6580],
        address: "Maddu, Gomba",
        students: 460,
        district: "Gomba",
        rating: 3.6
    },
    {
        id: 210,
        name: "Mpenja Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-880301",
        coordinates: [0.2000, 31.6400],
        address: "Mpenja, Gomba",
        services: ["Primary Care"],
        district: "Gomba",
        rating: 3.0
    },
    {
        id: 211,
        name: "Mpenja Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-880302",
        coordinates: [0.2020, 31.6420],
        address: "Mpenja, Gomba",
        students: 350,
        district: "Gomba",
        rating: 3.3
    },
    // KALANGALA DISTRICT - Additional Facilities
    {
        id: 212,
        name: "Kalangala Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-990012",
        coordinates: [-0.3140, 32.2320],
        address: "Kalangala, Bugala Island",
        students: 280,
        district: "Kalangala",
        rating: 3.3
    },
    {
        id: 213,
        name: "Bugoma Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-320701",
        coordinates: [-0.3200, 32.2400],
        address: "Bugoma, Kalangala",
        services: ["Primary Care"],
        district: "Kalangala",
        rating: 3.0
    },
    {
        id: 214,
        name: "Bugoma Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-320702",
        coordinates: [-0.3220, 32.2420],
        address: "Bugoma, Kalangala",
        students: 200,
        district: "Kalangala",
        rating: 3.2
    },
    {
        id: 215,
        name: "Mazinga Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-889901",
        coordinates: [-0.3000, 32.2200],
        address: "Mazinga, Kalangala",
        services: ["Primary Care"],
        district: "Kalangala",
        rating: 3.1
    },
    // KALUNGU DISTRICT - Additional Facilities
    {
        id: 216,
        name: "Kalungu Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-334401",
        coordinates: [-0.0880, 31.7530],
        address: "Kalungu Town",
        students: 520,
        district: "Kalungu",
        rating: 3.7
    },
    {
        id: 217,
        name: "Bukulula Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-112201",
        coordinates: [-0.0950, 31.7600],
        address: "Bukulula, Kalungu",
        services: ["Outpatient", "Maternity"],
        district: "Kalungu",
        rating: 3.3
    },
    {
        id: 218,
        name: "Bukulula Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-223301",
        coordinates: [-0.0970, 31.7620],
        address: "Bukulula, Kalungu",
        district: "Kalungu",
        openingHours: "24/7",
        officers: 18
    },
    {
        id: 219,
        name: "Bukulula Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-334402",
        coordinates: [-0.0930, 31.7580],
        address: "Bukulula, Kalungu",
        students: 480,
        district: "Kalungu",
        rating: 3.6
    },
    {
        id: 220,
        name: "Lukaya Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-990401",
        coordinates: [-0.1000, 31.7700],
        address: "Lukaya, Kalungu",
        services: ["Primary Care", "Maternity", "Laboratory"],
        district: "Kalungu",
        rating: 3.4
    },
    {
        id: 221,
        name: "Lukaya Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-990402",
        coordinates: [-0.0980, 31.7680],
        address: "Lukaya, Kalungu",
        students: 550,
        district: "Kalungu",
        rating: 3.8
    },
    // KYANKWANZI DISTRICT - Additional Facilities
    {
        id: 222,
        name: "Kyankwanzi Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-667701",
        coordinates: [1.0670, 31.7470],
        address: "Kyankwanzi Town",
        students: 420,
        district: "Kyankwanzi",
        rating: 3.4
    },
    {
        id: 223,
        name: "Butemba Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-445501",
        coordinates: [1.0800, 31.7600],
        address: "Butemba, Kyankwanzi",
        services: ["Primary Care"],
        district: "Kyankwanzi",
        rating: 3.1
    },
    {
        id: 224,
        name: "Butemba Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-556601",
        coordinates: [1.0820, 31.7620],
        address: "Butemba, Kyankwanzi",
        students: 360,
        district: "Kyankwanzi",
        rating: 3.3
    },
    {
        id: 225,
        name: "Ntwetwe Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-770501",
        coordinates: [1.0630, 31.7430],
        address: "Ntwetwe, Kyankwanzi",
        services: ["Outpatient", "Immunization"],
        district: "Kyankwanzi",
        rating: 3.2
    },
    {
        id: 226,
        name: "Ntwetwe Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-556602",
        coordinates: [1.0640, 31.7440],
        address: "Ntwetwe, Kyankwanzi",
        district: "Kyankwanzi",
        openingHours: "24/7",
        officers: 15
    },
    // KYOTERA DISTRICT - Additional Facilities
    {
        id: 227,
        name: "Kyotera Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-990012",
        coordinates: [-0.6210, 31.5010],
        address: "Kyotera Town",
        students: 680,
        district: "Kyotera",
        rating: 3.9
    },
    {
        id: 228,
        name: "Kalisizo Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-778801",
        coordinates: [-0.6300, 31.5100],
        address: "Kalisizo, Kyotera",
        services: ["Outpatient", "Maternity", "Laboratory"],
        district: "Kyotera",
        rating: 3.6
    },
    {
        id: 229,
        name: "Kalisizo Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-889901",
        coordinates: [-0.6320, 31.5120],
        address: "Kalisizo, Kyotera",
        district: "Kyotera",
        openingHours: "24/7",
        officers: 45
    },
    {
        id: 230,
        name: "Kalisizo Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-990013",
        coordinates: [-0.6280, 31.5080],
        address: "Kalisizo, Kyotera",
        students: 700,
        district: "Kyotera",
        rating: 4.0
    },
    {
        id: 231,
        name: "Kasasa Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-880601",
        coordinates: [-0.6100, 31.4900],
        address: "Kasasa, Kyotera",
        services: ["Primary Care"],
        district: "Kyotera",
        rating: 3.2
    },
    {
        id: 232,
        name: "Kasasa Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-880602",
        coordinates: [-0.6120, 31.4920],
        address: "Kasasa, Kyotera",
        students: 450,
        district: "Kyotera",
        rating: 3.5
    },
    // LWENGO DISTRICT - Additional Facilities
    {
        id: 233,
        name: "Lwengo Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-334401",
        coordinates: [-0.4110, 31.4210],
        address: "Lwengo Town",
        students: 500,
        district: "Lwengo",
        rating: 3.6
    },
    {
        id: 234,
        name: "Kkingo Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-112201",
        coordinates: [-0.4200, 31.4300],
        address: "Kkingo, Lwengo",
        services: ["Outpatient", "Maternity"],
        district: "Lwengo",
        rating: 3.3
    },
    {
        id: 235,
        name: "Kkingo Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-223301",
        coordinates: [-0.4220, 31.4320],
        address: "Kkingo, Lwengo",
        district: "Lwengo",
        openingHours: "24/7",
        officers: 20
    },
    {
        id: 236,
        name: "Kkingo Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-334402",
        coordinates: [-0.4180, 31.4280],
        address: "Kkingo, Lwengo",
        students: 480,
        district: "Lwengo",
        rating: 3.7
    },
    {
        id: 237,
        name: "Ndagwe Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-990701",
        coordinates: [-0.4000, 31.4100],
        address: "Ndagwe, Lwengo",
        services: ["Primary Care"],
        district: "Lwengo",
        rating: 3.0
    },
    {
        id: 238,
        name: "Ndagwe Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-990702",
        coordinates: [-0.4020, 31.4120],
        address: "Ndagwe, Lwengo",
        students: 380,
        district: "Lwengo",
        rating: 3.4
    },
    // LYANTONDE DISTRICT - Additional Facilities
    {
        id: 239,
        name: "Lyantonde Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-667701",
        coordinates: [-0.2910, 31.1610],
        address: "Lyantonde Town",
        students: 620,
        district: "Lyantonde",
        rating: 3.8
    },
    {
        id: 240,
        name: "Kabuyanda Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-445501",
        coordinates: [-0.3000, 31.1700],
        address: "Kabuyanda, Lyantonde",
        services: ["Outpatient", "Maternity"],
        district: "Lyantonde",
        rating: 3.4
    },
    {
        id: 241,
        name: "Kabuyanda Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-556601",
        coordinates: [-0.3020, 31.1720],
        address: "Kabuyanda, Lyantonde",
        district: "Lyantonde",
        openingHours: "24/7",
        officers: 22
    },
    {
        id: 242,
        name: "Kabuyanda Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-667702",
        coordinates: [-0.2980, 31.1680],
        address: "Kabuyanda, Lyantonde",
        students: 580,
        district: "Lyantonde",
        rating: 3.7
    },
    {
        id: 243,
        name: "Kinuuka Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-880801",
        coordinates: [-0.2800, 31.1500],
        address: "Kinuuka, Lyantonde",
        services: ["Primary Care"],
        district: "Lyantonde",
        rating: 3.2
    },
    {
        id: 244,
        name: "Kinuuka Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-880802",
        coordinates: [-0.2820, 31.1520],
        address: "Kinuuka, Lyantonde",
        students: 440,
        district: "Lyantonde",
        rating: 3.5
    },
    // MITYANA DISTRICT - Additional Facilities
    {
        id: 245,
        name: "Mityana Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-990012",
        coordinates: [0.4170, 32.0270],
        address: "Mityana Town",
        students: 750,
        district: "Mityana",
        rating: 4.0
    },
    {
        id: 246,
        name: "Busunju Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-889901",
        coordinates: [0.4300, 32.0400],
        address: "Busunju, Mityana",
        services: ["Outpatient", "Maternity", "Laboratory"],
        district: "Mityana",
        rating: 3.5
    },
    {
        id: 247,
        name: "Busunju Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-464-420201",
        coordinates: [0.4320, 32.0420],
        address: "Busunju, Mityana",
        district: "Mityana",
        openingHours: "24/7",
        officers: 25
    },
    {
        id: 248,
        name: "Busunju Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-990013",
        coordinates: [0.4280, 32.0380],
        address: "Busunju, Mityana",
        students: 620,
        district: "Mityana",
        rating: 3.9
    },
    {
        id: 249,
        name: "Kalangalo Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-464-420101",
        coordinates: [0.4100, 32.0200],
        address: "Kalangalo, Mityana",
        services: ["Primary Care"],
        district: "Mityana",
        rating: 3.3
    },
    {
        id: 250,
        name: "Kalangalo Primary School",
        type: "School",
        category: "Education",
        contact: "+256-464-420102",
        coordinates: [0.4120, 32.0220],
        address: "Kalangalo, Mityana",
        students: 480,
        district: "Mityana",
        rating: 3.6
    },
    // MUBENDE DISTRICT - Additional Facilities
    {
        id: 251,
        name: "Mubende Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-223301",
        coordinates: [0.5840, 31.3960],
        address: "Mubende Town",
        students: 720,
        district: "Mubende",
        rating: 3.9
    },
    {
        id: 252,
        name: "Kassanda Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-112201",
        coordinates: [0.5700, 31.3800],
        address: "Kassanda, Mubende",
        services: ["Outpatient", "Maternity"],
        district: "Mubende",
        rating: 3.4
    },
    {
        id: 253,
        name: "Kassanda Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-465-420201",
        coordinates: [0.5720, 31.3820],
        address: "Kassanda, Mubende",
        district: "Mubende",
        openingHours: "24/7",
        officers: 28
    },
    {
        id: 254,
        name: "Kassanda Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-223302",
        coordinates: [0.5680, 31.3780],
        address: "Kassanda, Mubende",
        students: 650,
        district: "Mubende",
        rating: 3.8
    },
    {
        id: 255,
        name: "Butoloogo Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-465-420101",
        coordinates: [0.5900, 31.4000],
        address: "Butoloogo, Mubende",
        services: ["Primary Care", "Laboratory"],
        district: "Mubende",
        rating: 3.3
    },
    {
        id: 256,
        name: "Butoloogo Primary School",
        type: "School",
        category: "Education",
        contact: "+256-465-420102",
        coordinates: [0.5920, 31.4020],
        address: "Butoloogo, Mubende",
        students: 520,
        district: "Mubende",
        rating: 3.6
    },
    // NAKASEKE DISTRICT - Additional Facilities
    {
        id: 257,
        name: "Nakaseke Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-556601",
        coordinates: [0.6810, 32.0810],
        address: "Nakaseke Town",
        students: 560,
        district: "Nakaseke",
        rating: 3.7
    },
    {
        id: 258,
        name: "Semuto Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-334401",
        coordinates: [0.6700, 32.0700],
        address: "Semuto, Nakaseke",
        services: ["Outpatient", "Maternity"],
        district: "Nakaseke",
        rating: 3.3
    },
    {
        id: 259,
        name: "Semuto Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-445501",
        coordinates: [0.6720, 32.0720],
        address: "Semuto, Nakaseke",
        district: "Nakaseke",
        openingHours: "24/7",
        officers: 18
    },
    {
        id: 260,
        name: "Semuto Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-556602",
        coordinates: [0.6680, 32.0680],
        address: "Semuto, Nakaseke",
        students: 540,
        district: "Nakaseke",
        rating: 3.7
    },
    {
        id: 261,
        name: "Kapeeka Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-770901",
        coordinates: [0.6900, 32.0900],
        address: "Kapeeka, Nakaseke",
        services: ["Primary Care"],
        district: "Nakaseke",
        rating: 3.1
    },
    {
        id: 262,
        name: "Kapeeka Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-770902",
        coordinates: [0.6920, 32.0920],
        address: "Kapeeka, Nakaseke",
        students: 420,
        district: "Nakaseke",
        rating: 3.5
    },
    // NAKASONGOLA DISTRICT - Additional Facilities
    {
        id: 263,
        name: "Nakasongola Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-778801",
        coordinates: [1.3110, 32.4610],
        address: "Nakasongola Town",
        students: 660,
        district: "Nakasongola",
        rating: 3.8
    },
    {
        id: 264,
        name: "Nabiswera Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-667701",
        coordinates: [1.3200, 32.4700],
        address: "Nabiswera, Nakasongola",
        services: ["Outpatient", "Maternity"],
        district: "Nakasongola",
        rating: 3.4
    },
    {
        id: 265,
        name: "Nabiswera Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-466-420201",
        coordinates: [1.3220, 32.4720],
        address: "Nabiswera, Nakasongola",
        district: "Nakasongola",
        openingHours: "24/7",
        officers: 20
    },
    {
        id: 266,
        name: "Nabiswera Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-778802",
        coordinates: [1.3180, 32.4680],
        address: "Nabiswera, Nakasongola",
        students: 580,
        district: "Nakasongola",
        rating: 3.7
    },
    {
        id: 267,
        name: "Lwampanga Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-466-420101",
        coordinates: [1.3000, 32.4500],
        address: "Lwampanga, Nakasongola",
        services: ["Primary Care"],
        district: "Nakasongola",
        rating: 3.2
    },
    {
        id: 268,
        name: "Lwampanga Primary School",
        type: "School",
        category: "Education",
        contact: "+256-466-420102",
        coordinates: [1.3020, 32.4520],
        address: "Lwampanga, Nakasongola",
        students: 480,
        district: "Nakasongola",
        rating: 3.5
    },
    // RAKAI DISTRICT - Additional Facilities
    {
        id: 269,
        name: "Rakai Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-990012",
        coordinates: [-0.7110, 31.5410],
        address: "Rakai Town",
        students: 520,
        district: "Rakai",
        rating: 3.6
    },
    {
        id: 270,
        name: "Kyotera Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-889901",
        coordinates: [-0.7200, 31.5500],
        address: "Kyotera Sub-county, Rakai",
        services: ["Outpatient", "Maternity", "HIV Testing"],
        district: "Rakai",
        rating: 3.5
    },
    {
        id: 271,
        name: "Kyotera Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-481-430201",
        coordinates: [-0.7220, 31.5520],
        address: "Kyotera Sub-county, Rakai",
        district: "Rakai",
        openingHours: "24/7",
        officers: 22
    },
    {
        id: 272,
        name: "Kyotera Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-990013",
        coordinates: [-0.7180, 31.5480],
        address: "Kyotera Sub-county, Rakai",
        students: 550,
        district: "Rakai",
        rating: 3.7
    },
    {
        id: 273,
        name: "Kifamba Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-481-430101",
        coordinates: [-0.7000, 31.5300],
        address: "Kifamba, Rakai",
        services: ["Primary Care"],
        district: "Rakai",
        rating: 3.3
    },
    {
        id: 274,
        name: "Kifamba Primary School",
        type: "School",
        category: "Education",
        contact: "+256-481-430102",
        coordinates: [-0.7020, 31.5320],
        address: "Kifamba, Rakai",
        students: 440,
        district: "Rakai",
        rating: 3.5
    },
    // SEMBABULE DISTRICT - Additional Facilities
    {
        id: 275,
        name: "Sembabule Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-334401",
        coordinates: [-0.0810, 31.4510],
        address: "Sembabule Town",
        students: 460,
        district: "Sembabule",
        rating: 3.4
    },
    {
        id: 276,
        name: "Lwemiyaga Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-112201",
        coordinates: [-0.0900, 31.4600],
        address: "Lwemiyaga, Sembabule",
        services: ["Outpatient", "Maternity"],
        district: "Sembabule",
        rating: 3.2
    },
    {
        id: 277,
        name: "Lwemiyaga Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-223301",
        coordinates: [-0.0920, 31.4620],
        address: "Lwemiyaga, Sembabule",
        district: "Sembabule",
        openingHours: "24/7",
        officers: 15
    },
    {
        id: 278,
        name: "Lwemiyaga Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-334402",
        coordinates: [-0.0880, 31.4580],
        address: "Lwemiyaga, Sembabule",
        students: 440,
        district: "Sembabule",
        rating: 3.3
    },
    {
        id: 279,
        name: "Mateete Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-990901",
        coordinates: [-0.0700, 31.4400],
        address: "Mateete, Sembabule",
        services: ["Primary Care"],
        district: "Sembabule",
        rating: 3.0
    },
    {
        id: 280,
        name: "Mateete Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-990902",
        coordinates: [-0.0720, 31.4420],
        address: "Mateete, Sembabule",
        students: 380,
        district: "Sembabule",
        rating: 3.2
    },
    // BUKOMANSIMBI DISTRICT - Additional Facilities
    {
        id: 281,
        name: "Bukomansimbi Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-667701",
        coordinates: [-0.1510, 31.6010],
        address: "Bukomansimbi Town",
        students: 420,
        district: "Bukomansimbi",
        rating: 3.5
    },
    {
        id: 282,
        name: "Kibinge Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-445501",
        coordinates: [-0.1600, 31.6100],
        address: "Kibinge, Bukomansimbi",
        services: ["Primary Care"],
        district: "Bukomansimbi",
        rating: 3.1
    },
    {
        id: 283,
        name: "Kibinge Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-772-556601",
        coordinates: [-0.1620, 31.6120],
        address: "Kibinge, Bukomansimbi",
        district: "Bukomansimbi",
        openingHours: "24/7",
        officers: 12
    },
    {
        id: 284,
        name: "Kibinge Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-667702",
        coordinates: [-0.1580, 31.6080],
        address: "Kibinge, Bukomansimbi",
        students: 390,
        district: "Bukomansimbi",
        rating: 3.4
    },
    {
        id: 285,
        name: "Bigasa Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-991001",
        coordinates: [-0.1400, 31.5900],
        address: "Bigasa, Bukomansimbi",
        services: ["Primary Care"],
        district: "Bukomansimbi",
        rating: 3.0
    },
    {
        id: 286,
        name: "Bigasa Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-991002",
        coordinates: [-0.1420, 31.5920],
        address: "Bigasa, Bukomansimbi",
        students: 350,
        district: "Bukomansimbi",
        rating: 3.3
    },
    // BUVUMA DISTRICT - Additional Facilities
    {
        id: 287,
        name: "Buvuma Hospital",
        type: "Hospital",
        category: "Healthcare",
        contact: "+256-414-991101",
        coordinates: [0.2510, 33.2510],
        address: "Buvuma Island",
        services: ["Emergency", "Surgery", "Maternity"],
        district: "Buvuma",
        beds: 50,
        openingHours: "24/7",
        rating: 3.4
    },
    {
        id: 288,
        name: "Buvuma Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-889901",
        coordinates: [0.2490, 33.2490],
        address: "Buvuma Island",
        students: 250,
        district: "Buvuma",
        rating: 3.2
    },
    {
        id: 289,
        name: "Nairambi Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-991102",
        coordinates: [0.2600, 33.2600],
        address: "Nairambi, Buvuma",
        services: ["Primary Care"],
        district: "Buvuma",
        rating: 3.0
    },
    {
        id: 290,
        name: "Nairambi Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-991103",
        coordinates: [0.2620, 33.2620],
        address: "Nairambi, Buvuma",
        students: 180,
        district: "Buvuma",
        rating: 3.1
    },
    // KAYUNGA DISTRICT - Additional Facilities
    {
        id: 291,
        name: "Kayunga Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-112201",
        coordinates: [0.7030, 32.9030],
        address: "Kayunga Town",
        students: 590,
        district: "Kayunga",
        rating: 3.7
    },
    {
        id: 292,
        name: "Galiraya Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-990012",
        coordinates: [0.7100, 32.9100],
        address: "Galiraya, Kayunga",
        services: ["Outpatient", "Maternity"],
        district: "Kayunga",
        rating: 3.4
    },
    {
        id: 293,
        name: "Galiraya Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-991301",
        coordinates: [0.7120, 32.9120],
        address: "Galiraya, Kayunga",
        district: "Kayunga",
        openingHours: "24/7",
        officers: 18
    },
    {
        id: 294,
        name: "Galiraya Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-112202",
        coordinates: [0.7080, 32.9080],
        address: "Galiraya, Kayunga",
        students: 560,
        district: "Kayunga",
        rating: 3.6
    },
    {
        id: 295,
        name: "Kangulumira Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-991201",
        coordinates: [0.6900, 32.8900],
        address: "Kangulumira, Kayunga",
        services: ["Primary Care", "Laboratory"],
        district: "Kayunga",
        rating: 3.3
    },
    {
        id: 296,
        name: "Kangulumira Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-991202",
        coordinates: [0.6920, 32.8920],
        address: "Kangulumira, Kayunga",
        students: 520,
        district: "Kayunga",
        rating: 3.5
    },
    // KIBOGA DISTRICT - Additional Facilities
    {
        id: 297,
        name: "Kiboga Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-334401",
        coordinates: [0.9030, 31.8030],
        address: "Kiboga Town",
        students: 540,
        district: "Kiboga",
        rating: 3.6
    },
    {
        id: 298,
        name: "Dwaniro Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-223301",
        coordinates: [0.9100, 31.8100],
        address: "Dwaniro, Kiboga",
        services: ["Outpatient", "Maternity"],
        district: "Kiboga",
        rating: 3.2
    },
    {
        id: 299,
        name: "Dwaniro Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-991501",
        coordinates: [0.9120, 31.8120],
        address: "Dwaniro, Kiboga",
        district: "Kiboga",
        openingHours: "24/7",
        officers: 16
    },
    {
        id: 300,
        name: "Dwaniro Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-334402",
        coordinates: [0.9080, 31.8080],
        address: "Dwaniro, Kiboga",
        students: 500,
        district: "Kiboga",
        rating: 3.5
    },
    {
        id: 301,
        name: "Kapeke Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-991401",
        coordinates: [0.8900, 31.7900],
        address: "Kapeke, Kiboga",
        services: ["Primary Care"],
        district: "Kiboga",
        rating: 3.1
    },
    {
        id: 302,
        name: "Kapeke Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-991402",
        coordinates: [0.8920, 31.7920],
        address: "Kapeke, Kiboga",
        students: 420,
        district: "Kiboga",
        rating: 3.4
    },
    // LUWEERO DISTRICT - Additional Facilities
    {
        id: 303,
        name: "Luweero Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-556601",
        coordinates: [0.8530, 32.5030],
        address: "Luweero Town",
        students: 680,
        district: "Luweero",
        rating: 3.8
    },
    {
        id: 304,
        name: "Bombo Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-445501",
        coordinates: [0.5800, 32.5300],
        address: "Bombo, Luweero",
        services: ["Outpatient", "Maternity", "Laboratory"],
        district: "Luweero",
        rating: 3.5
    },
    {
        id: 305,
        name: "Bombo Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-991701",
        coordinates: [0.5820, 32.5320],
        address: "Bombo, Luweero",
        district: "Luweero",
        openingHours: "24/7",
        officers: 50
    },
    {
        id: 306,
        name: "Bombo Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-556602",
        coordinates: [0.5780, 32.5280],
        address: "Bombo, Luweero",
        students: 680,
        district: "Luweero",
        rating: 3.9
    },
    {
        id: 307,
        name: "Wobulenzi Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-991601",
        coordinates: [0.7300, 32.5100],
        address: "Wobulenzi, Luweero",
        services: ["Primary Care", "Maternity"],
        district: "Luweero",
        rating: 3.4
    },
    {
        id: 308,
        name: "Wobulenzi Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-991602",
        coordinates: [0.7320, 32.5120],
        address: "Wobulenzi, Luweero",
        students: 640,
        district: "Luweero",
        rating: 3.8
    },
    // MPIGI DISTRICT - Additional Facilities
    {
        id: 309,
        name: "Mpigi Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-778801",
        coordinates: [0.2530, 32.3030],
        address: "Mpigi Town",
        students: 580,
        district: "Mpigi",
        rating: 3.7
    },
    {
        id: 310,
        name: "Buwama Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-772-667701",
        coordinates: [0.2400, 32.2900],
        address: "Buwama, Mpigi",
        services: ["Outpatient", "Maternity"],
        district: "Mpigi",
        rating: 3.3
    },
    {
        id: 311,
        name: "Buwama Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-991901",
        coordinates: [0.2420, 32.2920],
        address: "Buwama, Mpigi",
        district: "Mpigi",
        openingHours: "24/7",
        officers: 20
    },
    {
        id: 312,
        name: "Buwama Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-778802",
        coordinates: [0.2380, 32.2880],
        address: "Buwama, Mpigi",
        students: 560,
        district: "Mpigi",
        rating: 3.7
    },
    {
        id: 313,
        name: "Nkozi Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-991801",
        coordinates: [0.2600, 32.3100],
        address: "Nkozi, Mpigi",
        services: ["Primary Care", "Laboratory"],
        district: "Mpigi",
        rating: 3.4
    },
    {
        id: 314,
        name: "Nkozi Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-991802",
        coordinates: [0.2620, 32.3120],
        address: "Nkozi, Mpigi",
        students: 600,
        district: "Mpigi",
        rating: 3.8
    },
    // MUKONO DISTRICT - Additional Facilities
    {
        id: 315,
        name: "Mukono Primary School",
        type: "School",
        category: "Education",
        contact: "+256-772-889901",
        coordinates: [0.3530, 32.7530],
        address: "Mukono Town",
        students: 720,
        district: "Mukono",
        rating: 3.9
    },
    {
        id: 316,
        name: "Seeta Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-992001",
        coordinates: [0.3600, 32.7600],
        address: "Seeta, Mukono",
        services: ["Outpatient", "Maternity", "Laboratory"],
        district: "Mukono",
        rating: 3.6
    },
    {
        id: 317,
        name: "Seeta Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-992101",
        coordinates: [0.3620, 32.7620],
        address: "Seeta, Mukono",
        district: "Mukono",
        openingHours: "24/7",
        officers: 30
    },
    {
        id: 318,
        name: "Seeta Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-772-889902",
        coordinates: [0.3580, 32.7580],
        address: "Seeta, Mukono",
        students: 780,
        district: "Mukono",
        rating: 4.0
    },
    {
        id: 319,
        name: "Nama Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-992002",
        coordinates: [0.3700, 32.7700],
        address: "Nama, Mukono",
        services: ["Primary Care", "Maternity"],
        district: "Mukono",
        rating: 3.5
    },
    {
        id: 320,
        name: "Nama Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-992003",
        coordinates: [0.3720, 32.7720],
        address: "Nama, Mukono",
        students: 680,
        district: "Mukono",
        rating: 3.8
    },
    // WAKISO DISTRICT - Additional Facilities
    {
        id: 321,
        name: "Nansana Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-321900",
        coordinates: [0.3650, 32.5250],
        address: "Nansana, Wakiso",
        services: ["Outpatient", "Maternity", "Laboratory"],
        district: "Wakiso",
        rating: 3.7
    },
    {
        id: 322,
        name: "Nansana Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-322000",
        coordinates: [0.3670, 32.5270],
        address: "Nansana, Wakiso",
        district: "Wakiso",
        openingHours: "24/7",
        officers: 60
    },
    {
        id: 323,
        name: "Nansana Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-322100",
        coordinates: [0.3630, 32.5230],
        address: "Nansana, Wakiso",
        students: 850,
        district: "Wakiso",
        rating: 4.0
    },
    {
        id: 324,
        name: "Nansana Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-322200",
        coordinates: [0.3610, 32.5210],
        address: "Nansana, Wakiso",
        students: 620,
        district: "Wakiso",
        rating: 3.8
    },
    {
        id: 325,
        name: "Kira Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-322300",
        coordinates: [0.3700, 32.6300],
        address: "Kira, Wakiso",
        services: ["Outpatient", "Maternity"],
        district: "Wakiso",
        rating: 3.8
    },
    {
        id: 326,
        name: "Kira Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-322400",
        coordinates: [0.3720, 32.6320],
        address: "Kira, Wakiso",
        district: "Wakiso",
        openingHours: "24/7",
        officers: 55
    },
    {
        id: 327,
        name: "Kira Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-322500",
        coordinates: [0.3680, 32.6280],
        address: "Kira, Wakiso",
        students: 820,
        district: "Wakiso",
        rating: 4.1
    },
    {
        id: 328,
        name: "Kira Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-322600",
        coordinates: [0.3660, 32.6260],
        address: "Kira, Wakiso",
        students: 590,
        district: "Wakiso",
        rating: 3.9
    },
    {
        id: 329,
        name: "Makindye-Ssabagabo Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-322700",
        coordinates: [0.2800, 32.5800],
        address: "Makindye-Ssabagabo, Wakiso",
        services: ["Outpatient", "Maternity", "Laboratory"],
        district: "Wakiso",
        rating: 3.6
    },
    {
        id: 330,
        name: "Makindye-Ssabagabo Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-322800",
        coordinates: [0.2820, 32.5820],
        address: "Makindye-Ssabagabo, Wakiso",
        district: "Wakiso",
        openingHours: "24/7",
        officers: 50
    },
    {
        id: 331,
        name: "Makindye-Ssabagabo Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-322900",
        coordinates: [0.2780, 32.5780],
        address: "Makindye-Ssabagabo, Wakiso",
        students: 760,
        district: "Wakiso",
        rating: 3.9
    },
    {
        id: 332,
        name: "Makindye-Ssabagabo Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-323000",
        coordinates: [0.2760, 32.5760],
        address: "Makindye-Ssabagabo, Wakiso",
        students: 550,
        district: "Wakiso",
        rating: 3.7
    },
    {
        id: 333,
        name: "Busukuma Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-323100",
        coordinates: [0.1500, 32.5000],
        address: "Busukuma, Wakiso",
        services: ["Primary Care", "Maternity"],
        district: "Wakiso",
        rating: 3.5
    },
    {
        id: 334,
        name: "Busukuma Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-323200",
        coordinates: [0.1520, 32.5020],
        address: "Busukuma, Wakiso",
        students: 620,
        district: "Wakiso",
        rating: 3.8
    },
    {
        id: 335,
        name: "Kasanje Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-323300",
        coordinates: [0.3300, 32.5600],
        address: "Kasanje, Wakiso",
        services: ["Primary Care"],
        district: "Wakiso",
        rating: 3.3
    },
    {
        id: 336,
        name: "Kasanje Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-323400",
        coordinates: [0.3320, 32.5620],
        address: "Kasanje, Wakiso",
        students: 480,
        district: "Wakiso",
        rating: 3.6
    },
    {
        id: 337,
        name: "Namayumba Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-323500",
        coordinates: [0.3100, 32.4500],
        address: "Namayumba, Wakiso",
        services: ["Outpatient", "Maternity"],
        district: "Wakiso",
        rating: 3.4
    },
    {
        id: 338,
        name: "Namayumba Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-323600",
        coordinates: [0.3120, 32.4520],
        address: "Namayumba, Wakiso",
        district: "Wakiso",
        openingHours: "24/7",
        officers: 22
    },
    {
        id: 339,
        name: "Namayumba Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-323700",
        coordinates: [0.3080, 32.4480],
        address: "Namayumba, Wakiso",
        students: 580,
        district: "Wakiso",
        rating: 3.7
    },
    // KAMPALA DISTRICT - Additional Comprehensive Facilities
    {
        id: 340,
        name: "Kiruddu National Referral Hospital",
        type: "Hospital",
        category: "Healthcare",
        contact: "+256-414-541100",
        coordinates: [0.2800, 32.5900],
        address: "Makindye, Kampala",
        services: ["Emergency", "Surgery", "Maternity", "ICU", "Specialized Care"],
        district: "Kampala",
        beds: 800,
        openingHours: "24/7",
        rating: 4.3
    },
    {
        id: 341,
        name: "Nsambya Hospital",
        type: "Hospital",
        category: "Healthcare",
        contact: "+256-414-267051",
        coordinates: [0.2950, 32.5950],
        address: "Nsambya, Kampala",
        services: ["Emergency", "Surgery", "Maternity", "Cardiology"],
        district: "Kampala",
        beds: 350,
        openingHours: "24/7",
        rating: 4.4
    },
    {
        id: 342,
        name: "Mengo Hospital",
        type: "Hospital",
        category: "Healthcare",
        contact: "+256-414-270218",
        coordinates: [0.3050, 32.5700],
        address: "Mengo, Kampala",
        services: ["General Medicine", "Surgery", "Maternity", "Pediatrics"],
        district: "Kampala",
        beds: 300,
        openingHours: "24/7",
        rating: 4.2
    },
    {
        id: 343,
        name: "Lubaga Hospital",
        type: "Hospital",
        category: "Healthcare",
        contact: "+256-414-270218",
        coordinates: [0.3000, 32.5650],
        address: "Lubaga, Kampala",
        services: ["Emergency", "Surgery", "Maternity", "Outpatient"],
        district: "Kampala",
        beds: 250,
        openingHours: "24/7",
        rating: 4.1
    },
    {
        id: 344,
        name: "Kawempe Health Centre IV",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-541200",
        coordinates: [0.3700, 32.5600],
        address: "Kawempe, Kampala",
        services: ["Outpatient", "Maternity", "Laboratory", "HIV Testing"],
        district: "Kampala",
        rating: 3.8
    },
    {
        id: 345,
        name: "Kawempe Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-541300",
        coordinates: [0.3720, 32.5620],
        address: "Kawempe Division, Kampala",
        district: "Kampala",
        openingHours: "24/7",
        officers: 120
    },
    {
        id: 346,
        name: "Nakawa Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-541400",
        coordinates: [0.3300, 32.6100],
        address: "Nakawa Division, Kampala",
        district: "Kampala",
        openingHours: "24/7",
        officers: 110
    },
    {
        id: 347,
        name: "Makindye Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-541500",
        coordinates: [0.2900, 32.5950],
        address: "Makindye Division, Kampala",
        district: "Kampala",
        openingHours: "24/7",
        officers: 100
    },
    {
        id: 348,
        name: "Rubaga Police Station",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-541600",
        coordinates: [0.3050, 32.5650],
        address: "Rubaga Division, Kampala",
        district: "Kampala",
        openingHours: "24/7",
        officers: 95
    },
    {
        id: 349,
        name: "Kololo Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-541700",
        coordinates: [0.3250, 32.5950],
        address: "Kololo, Kampala",
        students: 950,
        district: "Kampala",
        rating: 4.4
    },
    {
        id: 350,
        name: "Nakivubo Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-541800",
        coordinates: [0.3180, 32.5850],
        address: "Nakivubo, Kampala",
        students: 720,
        district: "Kampala",
        rating: 3.9
    },
    {
        id: 351,
        name: "Mengo Senior School",
        type: "School",
        category: "Education",
        contact: "+256-414-541900",
        coordinates: [0.3070, 32.5720],
        address: "Mengo, Kampala",
        students: 1100,
        district: "Kampala",
        rating: 4.3
    },
    {
        id: 352,
        name: "Nakasero Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-542000",
        coordinates: [0.3190, 32.5840],
        address: "Nakasero, Kampala",
        students: 650,
        district: "Kampala",
        rating: 4.1
    },
    {
        id: 353,
        name: "Kibuli Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-542100",
        coordinates: [0.3050, 32.5900],
        address: "Kibuli, Kampala",
        students: 880,
        district: "Kampala",
        rating: 4.0
    },
    {
        id: 354,
        name: "Naguru Health Centre IV",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-542200",
        coordinates: [0.3350, 32.6000],
        address: "Naguru, Kampala",
        services: ["Outpatient", "Maternity", "Laboratory"],
        district: "Kampala",
        rating: 3.9
    },
    {
        id: 355,
        name: "Naguru Secondary School",
        type: "School",
        category: "Education",
        contact: "+256-414-542300",
        coordinates: [0.3370, 32.6020],
        address: "Naguru, Kampala",
        students: 820,
        district: "Kampala",
        rating: 4.2
    },
    {
        id: 356,
        name: "Katwe Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-542400",
        coordinates: [0.2950, 32.5750],
        address: "Katwe, Kampala",
        services: ["Primary Care", "Maternity", "Immunization"],
        district: "Kampala",
        rating: 3.6
    },
    {
        id: 357,
        name: "Katwe Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-542500",
        coordinates: [0.2970, 32.5770],
        address: "Katwe, Kampala",
        students: 680,
        district: "Kampala",
        rating: 3.8
    },
    {
        id: 358,
        name: "Wandegeya Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-542600",
        coordinates: [0.3320, 32.5700],
        address: "Wandegeya, Kampala",
        services: ["Outpatient", "HIV Testing", "Laboratory"],
        district: "Kampala",
        rating: 3.7
    },
    {
        id: 359,
        name: "Wandegeya Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-542700",
        coordinates: [0.3340, 32.5720],
        address: "Wandegeya, Kampala",
        students: 590,
        district: "Kampala",
        rating: 3.9
    },
    {
        id: 360,
        name: "Bwaise Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-542800",
        coordinates: [0.3500, 32.5500],
        address: "Bwaise, Kampala",
        services: ["Primary Care", "Maternity"],
        district: "Kampala",
        rating: 3.5
    },
    {
        id: 361,
        name: "Bwaise Police Post",
        type: "Police Station",
        category: "Public Safety",
        contact: "+256-414-542900",
        coordinates: [0.3520, 32.5520],
        address: "Bwaise, Kampala",
        district: "Kampala",
        openingHours: "24/7",
        officers: 40
    },
    {
        id: 362,
        name: "Bwaise Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-543000",
        coordinates: [0.3480, 32.5480],
        address: "Bwaise, Kampala",
        students: 720,
        district: "Kampala",
        rating: 3.7
    },
    {
        id: 363,
        name: "Kibuye Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-543100",
        coordinates: [0.2850, 32.5650],
        address: "Kibuye, Kampala",
        services: ["Outpatient", "Maternity", "Laboratory"],
        district: "Kampala",
        rating: 3.6
    },
    {
        id: 364,
        name: "Kibuye Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-543200",
        coordinates: [0.2870, 32.5670],
        address: "Kibuye, Kampala",
        students: 640,
        district: "Kampala",
        rating: 3.8
    },
    {
        id: 365,
        name: "Kamwokya Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-543300",
        coordinates: [0.3400, 32.5850],
        address: "Kamwokya, Kampala",
        services: ["Primary Care", "HIV Testing"],
        district: "Kampala",
        rating: 3.6
    },
    {
        id: 366,
        name: "Kamwokya Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-543400",
        coordinates: [0.3420, 32.5870],
        address: "Kamwokya, Kampala",
        students: 580,
        district: "Kampala",
        rating: 3.8
    },
    {
        id: 367,
        name: "Nakulabye Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-543500",
        coordinates: [0.3200, 32.5600],
        address: "Nakulabye, Kampala",
        services: ["Outpatient", "Maternity"],
        district: "Kampala",
        rating: 3.7
    },
    {
        id: 368,
        name: "Nakulabye Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-543600",
        coordinates: [0.3220, 32.5620],
        address: "Nakulabye, Kampala",
        students: 610,
        district: "Kampala",
        rating: 3.9
    },
    {
        id: 369,
        name: "Bugolobi Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-543700",
        coordinates: [0.3100, 32.6100],
        address: "Bugolobi, Kampala",
        services: ["Primary Care"],
        district: "Kampala",
        rating: 3.8
    },
    {
        id: 370,
        name: "Bugolobi Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-543800",
        coordinates: [0.3120, 32.6120],
        address: "Bugolobi, Kampala",
        students: 550,
        district: "Kampala",
        rating: 4.0
    },
    {
        id: 371,
        name: "Kyambogo University",
        type: "University",
        category: "Education",
        contact: "+256-414-286251",
        coordinates: [0.3600, 32.6200],
        address: "Kyambogo, Kampala",
        students: 25000,
        district: "Kampala",
        rating: 4.4
    },
    {
        id: 372,
        name: "Mbarara University Kampala Campus",
        type: "University",
        category: "Education",
        contact: "+256-414-543900",
        coordinates: [0.3250, 32.5900],
        address: "Kampala City",
        students: 3000,
        district: "Kampala",
        rating: 4.1
    },
    {
        id: 373,
        name: "Ndeeba Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-544000",
        coordinates: [0.2900, 32.5600],
        address: "Ndeeba, Kampala",
        services: ["Outpatient", "Maternity", "Laboratory"],
        district: "Kampala",
        rating: 3.6
    },
    {
        id: 374,
        name: "Ndeeba Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-544100",
        coordinates: [0.2920, 32.5620],
        address: "Ndeeba, Kampala",
        students: 670,
        district: "Kampala",
        rating: 3.8
    },
    {
        id: 375,
        name: "Kisugu Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-544200",
        coordinates: [0.2950, 32.6050],
        address: "Kisugu, Kampala",
        services: ["Primary Care", "Maternity"],
        district: "Kampala",
        rating: 3.5
    },
    {
        id: 376,
        name: "Kisugu Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-544300",
        coordinates: [0.2970, 32.6070],
        address: "Kisugu, Kampala",
        students: 600,
        district: "Kampala",
        rating: 3.7
    },
    {
        id: 377,
        name: "Mbuya Health Centre III",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-544400",
        coordinates: [0.3250, 32.6250],
        address: "Mbuya, Kampala",
        services: ["Outpatient", "Laboratory"],
        district: "Kampala",
        rating: 3.7
    },
    {
        id: 378,
        name: "Mbuya Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-544500",
        coordinates: [0.3270, 32.6270],
        address: "Mbuya, Kampala",
        students: 560,
        district: "Kampala",
        rating: 3.9
    },
    {
        id: 379,
        name: "Mutundwe Health Centre II",
        type: "Health Center",
        category: "Healthcare",
        contact: "+256-414-544600",
        coordinates: [0.2750, 32.5550],
        address: "Mutundwe, Kampala",
        services: ["Primary Care"],
        district: "Kampala",
        rating: 3.4
    },
    {
        id: 380,
        name: "Mutundwe Primary School",
        type: "School",
        category: "Education",
        contact: "+256-414-544700",
        coordinates: [0.2770, 32.5570],
        address: "Mutundwe, Kampala",
        students: 520,
        district: "Kampala",
        rating: 3.6
    }
];

// Export data
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { facilitiesData };
};
